### ISSUE TITLE
Editing the README

### ISSUE THREAD

**Issue by MadisonJMyers** [aloknsingh/ibm_r4ml_biganalytics#1]
Alok- great work! Please see my edits below. Many of my edits overlap with your other README.

- “Big Data Exploration (Stats, Visualization and Dimensionality reduction) and Preparation (cleaning, encoding, binning etc) using scalable open source package R4ML” should be “Big Data Preprocessing and Exploration using R4ML”
- Now add the “scalable R package” back in the paragraph below making it: “In this developer journey we will use R4ML, a scalable R package, running on IBM Data Science Experience (DSX) to perform various Machine Learning exercises.” (I also corrected the grammar so be sure to use the corrected sentence above.)
- Suggested edit: change the second line in the first paragraph to: “For those users who are unfamiliar with the Data Science Experience, DSX is an interactive, collaborative, cloud-based environment where data scientists, developers, and others interested in data science can use tools (e.g., RStudio, Jupyter Notebooks, Spark, etc.) to collaborate, share, and gather insight from their data.”
- Suggested edit: add periods at the end of all bullet/number points
- Change “Leverage R4ML to do the big data exploratory analysis and data preperation” to “Leverage R4ML to conduct preprocessing and exploratory analysis with big data.”
- “Large Scale Exploratory Analytics and Data Preparation” should be: “Large-scale exploratory analysis and data preparation”
- “Dimensionality reductions.” Should be: “Dimensionality reduction.”
- “How to use favorite R utilities on big data” should be: “How to use your favorite R utilities on big data.”
- “Since most of the time, a data scientist spent is on data exploration and preparation, this journey will acts as tutorials” should be something like: “Highlights the steps necessary to complete preprocessing and exploration.”
- “open source” should always be “open-source”
- Remove the word “fast” from the line describing IBM Bluemix Object Storage. That is redundant to speed.
- Again, add a period after each bullet point for consistency.
- Add a colon (:) after “R4ML Key Features”
- “Featured technologies” should have technologies capitalized (Technologies)
- “R4ML” under “Featured technologies” should have a colon after (“R4ML:”)
- For number 4 in the listed steps that are highlighted (“4. Save and Share”) should be “4. Save and share” for consistency with uppercase.
- Under the expanded step “1. Sign up for the Data Science Experience” sentence two needs changed from “By signing up for the Data Science Experience, two services: DSX-Spark and DSX-ObjectStore will be created in your Bluemix account.” to “By signing up for the Data Science Experience, two services will be created in your Bluemix account: DSX-Spark and DSX-ObjectStore.”
- “Login to your Bluemix account” should be “Login or create your Bluemix account” in case they do not have one.
- “ If not already used, name your service DSX-Spark.” should be “If the name has not already been used, name your service DSX-Spark so that you can keep track of it.” Or you can just say that the user can leave the defaults.
- Same with the Object Storage line.
- “Create the Notebook 1” should just be “Create Notebook 1”
- In step 3 in the first 3 bullet points “this” should be changed to “which”. Just my preference.

**Comment by aloknsingh** [comment]
fixed as per comments

**Comment by xwu0226** [comment]
@aloknsingh It would be ideal if @MadisonJMyers has a chance to do another check over your changes for accuracy and close the issue herself. Thanks!

**Comment by stevemar** [comment]
was this resolved? if so please close the issue.

**Comment by aloknsingh** [comment]
it is resolved , so closing
