### ISSUE TITLE
Editing the Notebook: R4ML_Introduction_Exploratory_DataAnalysis.ipynb

### ISSUE THREAD

**Issue by MadisonJMyers** [aloknsingh/ibm_r4ml_biganalytics#2]
Alok, this is a very interesting notebook. It think it will be quite compelling, especially with all of its visualizations. Please see my edits below:

- Change Title to be capitalized (Introduction and Exploratory Data Analysis)
- I believe the journey team wants number formatting to have a period after (1. , 2. , 3. etc.) Please change the numbering to be in accordance with that.
- Change “R4ML is the hybrid of SparkR and systemML algorithm. As stated in the R4ML mission to make BigData R , R like and three major goals of it i.e” to “R4ML is the hybrid of SparkR and SystemML. It’s mission is to make BigData R , R-like and to: ”
- “Support more bigdata ML algorithm and creating custom Algorithms” should be: “Support more big data ML algorithms.” and a new bullet point: “Support creating custom algorithms.”
- Change “R like” to “R-like”
- Change “R4ML is open source scalable Machine Learning Framework build using Apache Spark/SparkR and Apache SystemML,” to “R4ML is an open-source, scalable Machine Learning Framework built using Apache Spark/SparkR and Apache SystemML.” and move it above to be the first sentence in the 1.1 section.
- Then start the next sentence off with R4ML instead of It. (“R4ML allows R scripts…”)
- Add a “the” before “best features”
- A space is needed after that sentence’s period.
- “In this set of tutorial style notebooks, section, we will walk through the standard example, we an analyst or data-scientist will follow. i.e data precessing, data exploration, model creation, model tuning and model selection” should be: “In this set of tutorial style notebooks, we will walk through a standard example of a  data-scientist work flow. This includes data precessing, data exploration, model creation, model tuning and model selection.” 
- Delete “We will walk through the standard model creation and general things a data scientist would do it.” It is redundant.
- Put a colon (:) after “Let’s first load the relevant library”. (And add an ‘ in the Let’s)
- Remove “Here is the architecture of R4ML” and “R4ML Architecture” as they are unnecessary. 
- “Here are steps to install R4ML, this need to be done once for each user.” Should be: “Here are the steps to install R4ML. (This will only need to be done once for each user.)”
- 1.3 should be deleted as it is redundant. It repeats what is directly above it.
- All titles (the ones following numbers) should be consistently capitalized. (Change “Overview of data set” to “Overview of Data”
- Remove everything but the “Description” (add the line, “This is the free data set and reasonably sized (around 20GB and around 100M rows)” the “Format” and the “Source”
- Change “Data Loading” to “Load the Data”
- Lets needs to be Let’s
- Remove: “We have the airline dataset whose schema is as follows”
- Under 4.1, in the first sentence remove the second “we will”
- Change “Note user can use the various other exploratory analysis tools here.” To “Note: you can use the other exploratory analysis options here if you want to try them out.” (You can also delete this line if you want as it is unnecessary.)
- By stating: “It is well known that the preditive power of the features are highest if it is approximately guassian distributed.” You may alienate some readers. To avoid this, change it to something more open like: The *blank principle* “proves that the predictive power of the features are highest if it is approximately gaussian distributed.”
- Add an ‘ in the Let’s
- Capitalize the beginning of “Let’s create the histogram”
- Change to “Let’s create a histogram to see…”
- Change the period after “We also notice that due to the very constant distribution” to a comma (,)
- The third bullet point is confusing. Please rephrase.
- Change “Lets prune these dataset…” to “Let’s prune the dataset for further exploration”
- Choose “dataset” or data set” and stick with it throughout your entire project for consistency.
- Capitalize the “n” in note and remove the “also” from that sentence.
- Be careful not to alienate people again by making these steps seem easy. Someone may be new or unfamiliar. Because of this point remove “Using SparkR and our custom machine learning features (explained in later sections), it should be very straight forward exercise “
- “Since in general for example in lm model if features are co-related or collinear thant matrix solver will return the error while solving the system of equations” is unclear. There are many grammatical errors but it also does not make sense. Please rephrase.
- Remove “Now we know the relevant,” and capitalize the We to begin the sentence.
- Change “There are many R packages to do the job , we will use one of them i.e PerformanceAnalytics” to “Though there are many R packages that you can use, we are going to use “Performance Analytics””
- Change your first sentence in 4.2 to “This exploratory analysis can also be done in a nongraphical manner, using R4ML/SparkR.”
- Change the second sentence under 4.2 to: “For example, we can calculate the skewness and kurtosis to find whether a feature is close to gaussian or whether it has predictive power.”
- In the following sentence, capitalize the “The”
- Remove the comma from that sentence so it reads “that we”
- Change “do the some transformation” to “create a transformation” 
- “guassian” needs to be change to “gaussian” in all cases.
- All sentences should be capitalized.
- All sentences need punctuation at the end.
- In 4.2 and 5 make the sentences a paragraph.
- In 4.2 the sentence that starts “Similarly, one can user” should be “Similarly, one can use”
- “We, thus,” should be “In sum, we…”
- Commas go directly after the word it is following. Delete any spaces in between. “R4ML , a” should be “R4ML, a”
- Undercase “we” in the second sentence of 5.
- There is only one more notebook. Make it singular in sentence 3.

**Comment by aloknsingh** [comment]
wrt to "Remove everything but the “Description” (add the line, “This is the free data set and reasonably sized (around 20GB and around 100M rows)” the “Format” and the “Source”" 

I think it should have information about number of columns and source and it's usage.  and also it's source as user can download more data if needed and generally it is good to give actual references

**Comment by aloknsingh** [comment]
wrt "The third bullet point is confusing. Please rephrase." I changed to 
" Also note that there are some one sided [Power Law distribution](https://en.wikipedia.org/wiki/Power_law) e.g TaxiOut.We can use log transformation to make it approximately guassian.
"

**Comment by aloknsingh** [comment]
does this explanation for this sounds good?
From 
"Since in general for example in lm model if features are co-related or collinear thant matrix solver will return the error while solving the system of equations"

To

"One of the things you want to avoid is the co-related features i.e if we have one columns (say c4) a constant multiple of another column (say c3 )  then either one of c4 or c3 should be used. Since geometrically n columns corresponds to n edges of n dimensional rectangle or cube and if any other edges are dependent then the volume of the cube in n dimension will be zero. and this manifest it into the matrix solver error while solving system of equations)"

**Comment by aloknsingh** [comment]
fixed as per comments

**Comment by xwu0226** [comment]
@aloknsingh It would be ideal if @MadisonJMyers has a chance to do another check over your changes for accuracy and close the issue herself. Thanks!

**Comment by MadisonJMyers** [comment]
Hey @aloknsingh great progress! I've spotted a few minor edits in this notebook:

 - Under 1.1: "R4ML is an open-source, scalable Machine Learning Framework" should have a comma after "scalable"
 -Make sure at the end of all bullet points you consistently put periods.
 - Under 1.1: In the sentence "This includes data precessing,..." I think you were trying to say preprocessing? Please correct.
 - 1.2 is equivalent to 1.3 in scale so I would remove it and make 1.3 R4ML Architecture: Installation
 -1.4 's "Let's load the R4ML in R and start a new session" needs a period at the end.
 - Under 2: "There are many data sets and we have decided to use the airline dataset since" should have a colon after (:) and it would be better to change "since" to "because"
 - Again add periods after bullet points
 - "airline dataset is not always clean and building predictive model is not straight forward. Thus we can illustrate other points about the data preparation and analysis" should be "Airline and other datasets are not always clean and building predictive models for them is not always straight forward. Thus, we can illustrate other points about the data preparation and analysis."
 - "Here is the description of data. (you can also see the similar info by using help in R console)" should be: "Here is the description of data (you can also get help by using "help" in the R console):"
 - Under "Description" you need a period after the first sentence.
 - Under 4.1 there is a space between the sentence and the period. Delete the space.
 - Under 4.1.1 the "" does not end. Make sure to close that.
 - In that same section, in the last bullet point, "one sided" should be "one-sided"
 -"Using SparkR and our custom machine learning features (explained in later sections), it should be very straight forward exercise " should be something like: "By using SparkR and the custom machine learning features (explained in later sections), this exercise should be easier to execute."
 - I still find 4.1.2 confusing. Maybe try to edit this one more time for clarity.
 - In that same section, "And this manifest it into the matrix solver error while solving system of equations)" is very confusing. Try rewriting and don't forget to add a period at the end.
 - Another period is missing in the sentence that ends with "Performance Analytics"
 - In 4.2 "that is heavy tail on the right side" should have an "a" in front of "heavy tail"
 - "To get the best predictive power we might have to create a transformation so that the distribution is close to gaussian." needs a comma after "power".
 - "In Sum, we illustrated the idea that one can use the big data analytical, exploratory data analysis to make the future decisions about predictions" needs a period at the end and "Sum" should be "sum".
 - In section 5, capitalize the "how" in the first bullet point.

Great work! It has greatly improved. You're almost there.

**Comment by xwu0226** [comment]
@aloknsingh any progress on addressing the above comments?

**Comment by rhagarty** [comment]
@aloknsingh - you also need an architecture diagram and place it in 'doc/source/images/architecture.png'.

**Comment by stevemar** [comment]
i think this can be closed?

**Comment by MadisonJMyers** [comment]
@stevemart these issues were not all addressed. However, if you feel it looks good anyway, I can go ahead and close it.

**Comment by stevemar** [comment]
closing as per above comments

**Comment by aloknsingh** [comment]
closing as per comments
